export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const RESET_ENTHUSIASM = 'RESET_ENTHUSIASM';
export type RESET_ENTHUSIASM = typeof RESET_ENTHUSIASM;

export const ADD_CONSOLELOG = 'ADD_CONSOLELOG';
export type ADD_CONSOLELOG = typeof ADD_CONSOLELOG;